#!/bin/sh

[ -d /run/postgresql ] || sudo mkdir -p /run/postgresql && sudo chmod 777 /run/postgresql
tmux new-window -n server 'tmux split-window -v postgres ; source .venv/bin/activate && ./odoo/odoo-bin -c odoo.conf --dev=all'
